FROM node:20-alpine AS build
WORKDIR /app

COPY web/package*.json ./
RUN npm ci || npm install

COPY web/ .
RUN npm run build

FROM nginx:stable-alpine

RUN rm /etc/nginx/conf.d/default.conf

COPY infra/nginx.web.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
